# Generated by Django 4.2.7 on 2023-11-20 17:05

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("feedback", models.TextField(max_length=1000)),
                ("image", models.ImageField(upload_to=home.models.image_upload)),
            ],
        ),
    ]
