# Generated by Django 4.2.7 on 2023-11-20 01:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prevention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            (" Things You Should Do", "Things You Should Do"),
                            ("Things You Shouldn't Do", "Things You Shouldn't Do"),
                        ],
                        max_length=40,
                    ),
                ),
                ("image", models.ImageField(upload_to=home.models.image_upload)),
            ],
        ),
    ]
