# Generated by Django 4.2.7 on 2023-11-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_prevention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prevention",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Things You Should Do", "Things You Should Do"),
                    ("Things You Shouldn't Do", "Things You Shouldn't Do"),
                ],
                max_length=40,
            ),
        ),
    ]
